; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Settings shared by every environment below

[env]
platform = timsp430
board = lpmsp430g2553
framework = arduino
upload_protocol = tilib

; Sandbox environment

[env:lpmsp430g2553]
build_src_filter = +<main.cpp>

; Practice environments

[env:practice1]
build_src_filter = +<practice1.cpp>

[env:practice2]
build_src_filter = +<practice2.cpp>

[env:practice3]
build_src_filter = +<practice3.cpp>

[env:practice4]
build_src_filter = +<practice4.cpp>
